### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by wang429** [Ihellmasker/DrumBot64#7]
Seems like the bot crashes if it can't properly handle parsing some cases. Would be nice to handle error cases as gracefully as possible, so that the bot can process the next incoming sub/donation without manual restart.

Also, logging the message would be nice. Possible send to Discord channel? Or somewhere remote so that anyone can access it if the bot failed.

**Comment by Ihellmasker** [comment]
Any error that causes the bot to crash will trigger a restart, otherwise the donation will just be ignored, it's never needed a manual restart.

Also errors are logged, hence I can always get the error. Not gonna add discord connection into it though as that's way too much extra overhead on the bot. Crash errors aren't particularly useful to anyone but me really, and trying to add support to show the crashed lines somewhere else would probably cause further issues with those lines.
